// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Language is the predicate function for language builders.
type Language func(*sql.Selector)

// Project is the predicate function for project builders.
type Project func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)

// Ticket is the predicate function for ticket builders.
type Ticket func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
